### ISSUE TITLE
¿Qué podemos aprender o qué alianzas podemos establecer con este referente?: Redacción

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#10]
En **El modelo FRE inspiró el proyecto Delfín que a su vez inspiró esta propuesta. Es muy importante anotar que FRE tiene más estudiantes en colegios públicos que en colegios privados. En la página web [learning1to1](https://www.learning1to1.net/) se puede evidenciar que FRE no es solo una iniciativa privada. El sistema se ha implementado en un gran número de colegios públicos y en algunas Universidades. En el año 2020 tuve la oportunidad de hablar con John Jairo Parra Herrera, rector de la Institución Educativa [Isolda Echavarría](https://www.ieisoldaechavarria.edu.co/) [[Ech22](https://propuestavalor.readthedocs.io/es/latest/_unidad3/toread.html#id15)] de Itagüi, acerca de la implementación del sistema en este colegio público. El diálogo, inicialmente con Julio Fontán, y luego con John Jairo Parra me hace pensar que si el sistema público Colombiano pudo adaptarse a un cambio como el propuesto por FRE entonces la institución para la cual trabajo también podría hacerlo.** Eliminaría **inspiró el proyecto Delfín que a su vez inspiró esta propuesta. Es muy importante anotar que FRE**

**Comment by juanferfranco** [comment]
Atendido con el commit 7335e53
