### ISSUE TITLE
¿Qué podemos aprender o qué alianzas podemos establecer con este referente?: completar

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#11]
Luego de este fragmento: "**En [este](https://www.researchgate.net/publication/348336687_El_Modelo_de_Educacion_Relacional_Fontan_De_la_practica_a_la_teoria) [[CM21](https://propuestavalor.readthedocs.io/es/latest/_unidad3/toread.html#id3)] libro se puede encontrar una sustentación científica del modelo FRE. Dicho trabajo fue desarrollado en conjunto por el equipo de investigación de FRE y la Universidad de Barcelona. Estos últimos ofrecen un [posgrado](https://www.il3.ub.edu/postgrado-modelo-educacion-relacional) [[dB21](https://propuestavalor.readthedocs.io/es/latest/_unidad3/toread.html#id16)] en el modelo**." Sería importante dar un contexto sobre qué es concretamente FRE o al menos dar una idea central.

**Comment by juanferfranco** [comment]
Creo que las secciones Propuesta de valor y ¿Por qué este referente inspira la propuesta? dan el contexto de qué es concretamente FRE. Creo que dar la idea central en este punto es redundar con lo dicho en las secciones anteriores cuando se menciona que FRE es centrado en el estudiante, de tiempo variable, pero calidad constante, que busca el mastery learning, etc.

¿Qué opinas?

**Comment by juanferfranco** [comment]
Pauli, cerraré este issue, pero si hace falta lo volvemos a abrir
