### ISSUE TITLE
¿Qué podemos aprender o qué alianzas podemos establecer con este referente? Corrección: 

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#13]
"01-edu propone un cambio radical en la relación profesor estudiante y es el análisis de esa propuesta lo que" cambiar por: "01-edu **plantea** un cambio radical en la relación profesor estudiante y es el análisis de esa propuesta lo que"

**Comment by juanferfranco** [comment]
Fixed with commit e400202
