### ISSUE TITLE
London Interdisciplinary School - Propuesta de valor: corrección en redacción

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#14]
Se sugiere para disminuir las citas cambiar el apartado por el siguiente texto:

De acuerdo con la propuesta de LIS los líderes en los diversos campos y disciplinas requieren de competencias y habilidades que les posibiliten enfrentar los retos de un mundo cambiante y complejo. En este orden de ideas, resulta imprescindible la articulación de los saberes a fin de poder analizar, reflexionar y proponer alternativas y soluciones a problemas reales. La universidad debe entonces plantear sinergias entre grupos diversos (académicos, empresarios y educadores) que posibiliten centrar su interés en la enseñanza más que en la investigación como lo propone este modelo. 

"El equipo de LIS incluye filósofos, epidemiólogos, artistas, periodistas, científicos del comportamiento y matemáticos, así como empresarios y profesionales". Esto posibilita que la inteligencia colectiva deje de ser un marco organizativo teórico a un campo real de realización en donde se hace palpable la interdisciplinariedad. Desde LIS consideran que estos diálogos posibiliten nuevas formas de comprender y experimentar en el mundo, puesto que se superan las fronteras y se desarrollan conexiones para encontrar alternativas.

**Comment by juanferfranco** [comment]
fixed with commit 9110ec0
