### ISSUE TITLE
Propuesta de valor - corrección

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#15]
En el último párrafo: "pero dan 3 razones para hacerlo:

- La especialización temprana limita la exploración de la carrera.
- Integrar el conocimiento genera mejores resultados.
- Los problemas son interdisciplinarios, por lo que los planes de estudio también deberían serlo"

Se sugiere cambiar la última por:

"- Los planes de estudio deberían basarse en problemas de naturaleza interdisciplinaria".

**Comment by juanferfranco** [comment]
fixed with commit aca566e
