### ISSUE TITLE
Descripción del programa - INQUIETUD

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#19]
Profe puede ser por mi falta de contexto pero no me queda claro qué es la teoría de control. Entiendo que no es el lugar par un despliegue grande, no obstante, al ser el argumento que se sugiere par hablar de ingeniería y no de diseño me parece importante una mínima aclaración de a qué se refiere con teoría del control.

**Comment by juanferfranco** [comment]
Pauli efectivamente se podría ampliar para una siguiente versión del documento. Dejaré este issue abierto para abordar el asunto más adelante. Creo que incluso un buen punto de partida puede ser wikipedia: https://es.wikipedia.org/wiki/Teor%C3%ADa_del_control

**Comment by juanferfranco** [comment]
fixed with commit dbf9747
