### ISSUE TITLE
Introducción 

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#2]
Aunque es clara y directa la relación con el objetivo 4 de desarrollo sostenible, me parece importante sugerir conexiones con el 8 y 9. Asimismo, sería interesante justificar esta relación de forma puntual. Un ejemplo podría ser:

Objetivo 4 porque creamos una oferta educativa de acuerdo con las tendencias formativas y con las necesidades en un contexto cambiante y lleno de desafíos.

Objetivo 8: porque conectamos el conocimiento y la comprensión para actuar y transformar el mundo, mediante la resolución de problemas que afectan los distintos ámbitos de la vida.

Objetivo 9: porque entendemos que la innovación implica cosntruir rutas y formas de abordaje distintas en relación con problemas conocidos. Los retos conocidos requieren nuevos abordajes.

**Comment by juanferfranco** [comment]
Se atiende con el commit a72098a
