### ISSUE TITLE
Problemas abordados por el programa - Corrección

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#20]
Se sugiere cambiar: "Cada uno de estos ámbitos produce problemas que dificultan el proceso de desarrollo y aprendizaje del aprendiz". por "Cada uno de estos ámbitos produce problemas que dificultan el proceso de desarrollo y aprendizaje del **estudiante**".

**Comment by juanferfranco** [comment]
Pauli. La palabra aprendiza busca darle un matiz más amplio al programa. Pero si consideras podemos cambiarla en todo el documento

**Comment by juanferfranco** [comment]
Luego de hablar en persona acordamos con Pauli dejar la palabra aprendiz porque implica una actitud hacia el aprendizaje que no está enmarcada en el rol tradicional de estudiante.
