### ISSUE TITLE
Problemas abordados por el programa - Redacción

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#21]
En "que abordan los problemas relacionados con:

Se sugiere realizar los siguientes cambios:

1. "Afronta las condiciones ambientales o externas, es decir, las condiciones que conducen a un aprendizaje óptimo. Por ejemplo, la arquitectura de un ambiente físico o virtual de aprendizaje, las estructuras sociales, la mentalidad de los aprendices, hábitos y prácticas de los aprendices". Por "**Afrontar** las condiciones ambientales o externas, es decir, las condiciones que conducen a un aprendizaje óptimo. Por ejemplo, la arquitectura de un ambiente físico o virtual de aprendizaje, las estructuras sociales, la mentalidad de los aprendices, hábitos y prácticas de los aprendices".

2. "Diseño curricular" por "**Realizar propuestas que posibiliten la transformación en el diseño curricular**".

3. "Desarrollo de tecnologías educativas" por "**Desarrollar tecnologías educativas para afrontar retos concretos**".

4. "Analítica del aprendizaje" por "**Posibilitar la analítica del aprendizaje para el mejoramiento continuo de los procesos**".

5. "Aprendizaje personalizado" por "**Implementar procesos y prácticas que posibiliten el aprendizaje personalizado**".

6. No existe el verbo "Instrumentar" - no creo que "instrumentalizar sea lo que quieres decir, pero sería oportuno pensar en otra palabra.

**Comment by juanferfranco** [comment]
fixed with commit 887255f
