### ISSUE TITLE
Acercamiento a las competencias del programa - Corrección

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#22]
Se sugiere cambiar "Para acercarse a una posible propuesta de competencias para el ingeniería del aprendizaje es importante recordar algunas definición" por "Para acercarse a una posible propuesta de competencias para **la** ingeniería del aprendizaje es importante recordar algunas definición".

**Comment by juanferfranco** [comment]
fixed with commit 1c0139d
