### ISSUE TITLE
Introducción Completar

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#3]
Después de "**Esta documentación es el resultado de un proceso de reflexión personal, de búsqueda y análisis para proponer un prototipo de un nuevo programa educativo disruptivo e innovador**" es importante justificar que es disruptiva e innovadora porque posee una organización curricular diferenciadqa que se cosntituye en una forma de abordar los problemas reales.

**Comment by juanferfranco** [comment]
Se atiende con el commit 8004e68
