### ISSUE TITLE
El camino recorrido hasta ahora: enlace

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#6]
Parecería que el título **El camino recorrido hasta ahora** tiene un enlace al lado pero no lleva a ningún lugar.

**Comment by juanferfranco** [comment]
Estos son enlaces permanentes a la sección. Esto permite que una persona pueda referenciar partes concretas del documento. Por ejemplo, saltar directamente a la sección sobre el modelo fontán:
https://propuestavalor.readthedocs.io/es/latest/_unidad1/referentes.html#modelo-relacional-fontan
