### ISSUE TITLE
¿Por qué este referente inspira la propuesta?: idea repetida

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#7]
Dado que desde el párrafo anterior se ha dejado claro que la propuesta se basa en tiempo variable y calidad constante, creo pertienente borrar esta afirmación "Esta propuesta está basada en el mismo principio de tiempo variable, pero calidad constante". Y pegar "Realmente se privilegia el aprendizaje vinculándolo con el concepto de" al párrafo anterior.

**Comment by juanferfranco** [comment]
Se atiende con el commit 2076db0
