### ISSUE TITLE
¿Por qué este referente inspira la propuesta?: breve contexto

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#8]
Sugiero que cuando se dice: **[Este](https://youtu.be/-MTRxRO5SRA) [[TED16](https://propuestavalor.readthedocs.io/es/latest/_unidad3/toread.html#id44)] video TED de Salman khan lo explica muy bien.** Propongamos un contexto, propongo este ejemplo:
La base sólida de una propuesta educativa debe perseguir el aprendizaje para la comprensión como uno de sus objetivos principales. Esto implica que más allá del seguimiento estricto de un plan de estudios que en muchas ocasiones se lleva a cabo sin tener en cuenta los niveles de apropiación verificables de los estudiantes, lo realmente importante es consolidar el aprendizaje desde una perspectiva autónoma que posibilite agenciar lo que se logra comprender, así como aquellos procesos que requieren de mayor repaso y concentración. Ciertamente desde esta perspectiva no todos irán al mismo ritmo, no obstante se posibilitará que lleguen al mejor nivel posible de acuerdo con las características propias de cada estudiante.

**Comment by juanferfranco** [comment]
Atendido con el commit f310d05
