### ISSUE TITLE
¿Por qué este referente inspira la propuesta?: Redacción

### ISSUE THREAD

**Issue by paulinagomez1** [juanferfranco/propuestaValor#9]
En esta oración: **¿Por qué? Porque esto permite que una persona pueda avanzar en su proceso de formación con bases firmes y fortalecer su mentalidad** eliminaría ¿Por qué? puesto que se ha hecho uso varias veces en un texto corto.

**Comment by juanferfranco** [comment]
Atentido con el commit 0d3723d
